/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import static View.Produtos_GUI.id_txt;
import static View.Produtos_GUI.nomepro_txt;
import static View.Produtos_GUI.preco_txt;
import static View.Produtos_GUI.tipo_txt;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaua
 */
public class Vendas_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Vendas_GUI
     */
    public Vendas_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cpf_text = new javax.swing.JLabel();
        valortl_txt = new javax.swing.JTextField();
        id_compra_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        quant_text = new javax.swing.JLabel();
        produto_text = new javax.swing.JLabel();
        preco_text = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nome_text = new javax.swing.JLabel();
        limpar_BTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barrinha = new javax.swing.JMenuBar();
        INICIO = new javax.swing.JMenu();
        inicio = new javax.swing.JMenuItem();
        PRODUTO = new javax.swing.JMenu();
        produto = new javax.swing.JMenuItem();
        CAIXA = new javax.swing.JMenu();
        caixa = new javax.swing.JMenuItem();
        VENDAS = new javax.swing.JMenu();
        vendas = new javax.swing.JMenuItem();
        SAIR = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor Total");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 100, 90, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dados do Cliente:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 40, 160, 40);

        cpf_text.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(cpf_text);
        cpf_text.setBounds(610, 140, 150, 30);
        jPanel1.add(valortl_txt);
        valortl_txt.setBounds(130, 100, 110, 30);
        jPanel1.add(id_compra_txt);
        id_compra_txt.setBounds(140, 40, 60, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nome");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(560, 90, 50, 40);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CPF");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 130, 50, 40);

        jTable1.setBackground(new java.awt.Color(103, 103, 103));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_compra", "Nome", "Metodo_pagaento", "Produtos", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 880, 230);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ID_compra");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(50, 30, 100, 40);
        jPanel1.add(quant_text);
        quant_text.setBounds(160, 220, 140, 30);
        jPanel1.add(produto_text);
        produto_text.setBounds(150, 140, 130, 30);
        jPanel1.add(preco_text);
        preco_text.setBounds(140, 180, 140, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lupa (1).png"))); // NOI18N
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 40, 50, 30);

        nome_text.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(nome_text);
        nome_text.setBounds(610, 100, 150, 30);

        limpar_BTN.setBackground(new java.awt.Color(255, 255, 51));
        limpar_BTN.setForeground(new java.awt.Color(0, 0, 0));
        limpar_BTN.setText("Limpar");
        limpar_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_BTNActionPerformed(evt);
            }
        });
        jPanel1.add(limpar_BTN);
        limpar_BTN.setBounds(330, 70, 130, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fundo2.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 880, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 530);

        barrinha.setBackground(new java.awt.Color(0, 0, 0));
        barrinha.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.MatteBorder(null)));

        INICIO.setBackground(new java.awt.Color(0, 0, 0));
        INICIO.setForeground(new java.awt.Color(255, 255, 255));
        INICIO.setText("Início");
        INICIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIOActionPerformed(evt);
            }
        });

        inicio.setText("Tela Inicial");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });
        INICIO.add(inicio);

        barrinha.add(INICIO);

        PRODUTO.setBackground(new java.awt.Color(0, 0, 0));
        PRODUTO.setForeground(new java.awt.Color(255, 255, 255));
        PRODUTO.setText("Produtos");

        produto.setText("Produtos");
        produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoActionPerformed(evt);
            }
        });
        PRODUTO.add(produto);

        barrinha.add(PRODUTO);

        CAIXA.setBackground(new java.awt.Color(0, 0, 0));
        CAIXA.setForeground(new java.awt.Color(255, 255, 255));
        CAIXA.setText("Caixa");
        CAIXA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAIXAActionPerformed(evt);
            }
        });

        caixa.setText("Caixa");
        caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaActionPerformed(evt);
            }
        });
        CAIXA.add(caixa);

        barrinha.add(CAIXA);

        VENDAS.setBackground(new java.awt.Color(0, 0, 0));
        VENDAS.setForeground(new java.awt.Color(255, 255, 255));
        VENDAS.setText("Vendas");
        VENDAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VENDASActionPerformed(evt);
            }
        });

        vendas.setText("Vendas");
        vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasActionPerformed(evt);
            }
        });
        VENDAS.add(vendas);

        barrinha.add(VENDAS);

        SAIR.setBackground(new java.awt.Color(0, 0, 0));
        SAIR.setForeground(new java.awt.Color(255, 255, 255));
        SAIR.setText("Sair");
        SAIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIRActionPerformed(evt);
            }
        });

        sair.setText("jMenuItem7");
        SAIR.add(sair);

        barrinha.add(SAIR);

        setJMenuBar(barrinha);

        setSize(new java.awt.Dimension(877, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        // TODO add your handling code here:
        new Inicio_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_inicioActionPerformed

    private void INICIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INICIOActionPerformed

    private void produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoActionPerformed
        // TODO add your handling code here:
        new Produtos_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_produtoActionPerformed

    private void caixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaActionPerformed
        // TODO add your handling code here:
        new Caixa_GUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_caixaActionPerformed

    private void CAIXAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAIXAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAIXAActionPerformed

    private void VENDASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VENDASActionPerformed
dispose();
    }//GEN-LAST:event_VENDASActionPerformed

    private void SAIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SAIRActionPerformed

    private void vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasActionPerformed
      new Vendas_GUI().setVisible(true);
      dispose();
              
              
    }//GEN-LAST:event_vendasActionPerformed

    private void limpar_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_BTNActionPerformed
        id_compra_txt.setText("");
        valortl_txt.setText("");
       
    }//GEN-LAST:event_limpar_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CAIXA;
    private javax.swing.JMenu INICIO;
    private javax.swing.JMenu PRODUTO;
    private javax.swing.JMenu SAIR;
    private javax.swing.JMenu VENDAS;
    public static javax.swing.JMenuBar barrinha;
    private javax.swing.JMenuItem caixa;
    private javax.swing.JLabel cpf_text;
    private javax.swing.JTextField id_compra_txt;
    private javax.swing.JMenuItem inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton limpar_BTN;
    private javax.swing.JLabel nome_text;
    private javax.swing.JLabel preco_text;
    private javax.swing.JMenuItem produto;
    private javax.swing.JLabel produto_text;
    private javax.swing.JLabel quant_text;
    private javax.swing.JMenuItem sair;
    private javax.swing.JTextField valortl_txt;
    private javax.swing.JMenuItem vendas;
    // End of variables declaration//GEN-END:variables
}
